{
 "title": "CRUD App Observability",
 "tags": [
  "crud",
  "kubernetes"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(crud_http_requests_total[1m]))",
     "legendFormat": "requests/sec"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(crud_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95 latency"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(crud_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p50 latency"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(crud_http_requests_total{status=~\"5..\"}[1m]))",
     "legendFormat": "5xx/sec"
    },
    {
     "expr": "sum(rate(crud_http_requests_total{status=~\"4..\"}[1m]))",
     "legendFormat": "4xx/sec"
    }
   ]
  }
 ]
}